-- create tables
CREATE TABLE Students (
    StudentID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FullName VARCHAR2(100),
    BirthDate DATE,
    Address VARCHAR2(255)
);
/

CREATE TABLE Subjects (
    SubjectID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SubjectName VARCHAR2(100)
);
/

CREATE TABLE ExamResults (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    StudentID NUMBER,
    SubjectID NUMBER,
    Score NUMBER(4, 2),
    FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
    FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
);
/

-- insert data
DECLARE
  subjectName NVARCHAR2(100);
BEGIN
  FOR i IN 1..9 LOOP
    CASE i
      WHEN 1 THEN SubjectName := N'Ng? van';
      WHEN 2 THEN SubjectName := N'Toán h?c';
      WHEN 3 THEN SubjectName := N'L?ch s?';
      WHEN 4 THEN SubjectName := N'Ð?a lý';
      WHEN 5 THEN SubjectName := N'V?t lý';
      WHEN 6 THEN SubjectName := N'Hóa h?c';
      WHEN 7 THEN SubjectName := N'Sinh h?c';
      WHEN 8 THEN SubjectName := N'Ngo?i ng?';
      WHEN 9 THEN SubjectName := N'Giáo d?c công dân';
    END CASE;

    INSERT INTO Subjects (SubjectName) VALUES (subjectName);
  END LOOP;
  COMMIT;
END;
/

DECLARE
  subjectName NVARCHAR2(100);
BEGIN
  FOR i IN 1..9 LOOP
    CASE i
      WHEN 1 THEN subjectName := N'Literature';
      WHEN 2 THEN subjectName := N'Mathematics';
      WHEN 3 THEN subjectName := N'History';
      WHEN 4 THEN subjectName := N'Geography';
      WHEN 5 THEN subjectName := N'Physics';
      WHEN 6 THEN subjectName := N'Chemistry';
      WHEN 7 THEN subjectName := N'Biology';
      WHEN 8 THEN subjectName := N'Foreign Language';
      WHEN 9 THEN subjectName := N'Civic Education';
    END CASE;

    INSERT INTO Subjects (SubjectName) VALUES (subjectName);
  END LOOP;
  COMMIT;
END;
/

BEGIN
  FOR i IN 1..50 LOOP
    INSERT INTO Students (FullName, BirthDate, Address)
    VALUES ('Student ' || i, SYSDATE - TRUNC(DBMS_RANDOM.VALUE(365*18, 365*25)), 'Address ' || i);
  END LOOP;
  COMMIT;
END;
/

DECLARE
  studentID NUMBER;
  subjectID NUMBER;
  score NUMBER(4, 2);
BEGIN
  FOR i IN 1..200 LOOP
    studentID := LPAD(TRUNC(DBMS_RANDOM.VALUE(1, 50)), 3, '0');
    subjectID := LPAD(TRUNC(DBMS_RANDOM.VALUE(1, 9)), 2, '0');
    score := TRUNC(DBMS_RANDOM.VALUE(1, 10), 2); 
    INSERT INTO ExamResults (StudentID, SubjectID, Score)
    VALUES (studentID, subjectID, score);
  END LOOP;
  COMMIT;
END;
/
